Update azure-veracode-api-wrapper.yml for Azure Pipelines

diff --git a/azure-veracode-api-wrapper.yml b/azure-veracode-api-wrapper.yml
--- a/azure-veracode-api-wrapper.yml
+++ b/azure-veracode-api-wrapper.yml
@@ -39,17 +39,13 @@ steps:
 #     importResults: false
 #     maximumWaitTime: '360'
 
-- task: PowerShell@2
-  displayName: Veracode Java API Wrapper
-  inputs:
-    targetType: 'inline'
-    script: |
-      WRAPPER_VERSION=`curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1`
-      if `wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION.jar -O VeracodeJavaAPI.jar`; then
-                      chmod 755 VeracodeJavaAPI.jar
-                      echo '[INFO] SUCCESSFULLY DOWNLOADED WRAPPER'
-        else
-                      echo '[ERROR] DOWNLOAD FAILED'
-                      exit 1
-      fi
-      java -jar VeracodeJavaAPI.jar -action UploadAndScan -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -deleteincompletescan 1 -createprofile false -appname "Verademo  -version "$(build.buildNumber)" -filepath $(System.DefaultWorkingDirectory)/app/target/verademo.war
+- script: |
+    WRAPPER_VERSION=$(curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1)
+    if wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION.jar -O VeracodeJavaAPI.jar; 
+    then
+        chmod 755 VeracodeJavaAPI.jar
+        echo '[INFO] SUCCESSFULLY DOWNLOADED WRAPPER'
+    else
+        echo '[ERROR] DOWNLOAD FAILED'
+        exit 1
+    fi
